services:
  cdc_webapp:
    build:
      context: ./cdc-webapp
    env_file: "webapp.env"
    ports:
      - "3001:3000"
    depends_on:
      - cdc_consumer

  cdc_topic_creator:
    build:
      context: ./cdc-topic-creator
    environment:
      KAFKA_TOPIC: cdc-changes
      KAFKA_BROKER_ADDR: broker:29092
    depends_on:
      - broker
    restart: on-failure

  cdc_consumer:
    build:
      context: ./cdc-consumer
    environment:
      KAFKA_TOPIC: cdc-changes
      KAFKA_BROKER_ADDR: broker:29092
      WS_SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - broker
      - cdc_ingestor
      - cdc_topic_creator

  cdc_ingestor:
    build:
      context: ./cdc-ingestor
    environment:
      KAFKA_TOPIC: cdc-changes
      KAFKA_BROKER_ADDR: broker:29092
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
    depends_on:
      - postgres
      - broker
      - cdc_topic_creator

  postgres:
    build:
      context: ./custom-images
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./configs/postgresql.conf:/etc/postgresql.conf
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Q

  kafka-ui:
    image: kafbat/kafka-ui:main
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    depends_on:
      - broker
