/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.aloussase.cdc;

import org.apache.kafka.clients.admin.AdminClientConfig;
import org.apache.kafka.clients.admin.KafkaAdminClient;
import org.apache.kafka.clients.admin.NewTopic;

import java.util.List;
import java.util.Objects;
import java.util.Properties;

public class App {
    public static void main(String[] args) {
        final var brokerAddr = Objects.requireNonNull(System.getenv("KAFKA_BROKER_ADDR"), "Broker address is not set");

        final var props = new Properties();
        props.put(AdminClientConfig.BOOTSTRAP_SERVERS_CONFIG, brokerAddr);

        final var topicName = Objects.requireNonNull(System.getenv("KAFKA_TOPIC"), "Topic name is not set");

        final var topic = new NewTopic(topicName, 1, (short)1);

        try (final var adminClient = KafkaAdminClient.create(props)) {
            adminClient.createTopics(List.of(topic));
        } catch (Exception ex) {
            ex.printStackTrace();
            System.exit(1);
        }

        System.out.println("Create topic: " + topic);
        System.exit(0);
    }
}
